//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.Cine.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CineConexion : DbContext
    {
        public CineConexion()
            : base("name=CineConexion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Calificacione> Calificaciones { get; set; }
        public DbSet<Cartelera> Carteleras { get; set; }
        public DbSet<Genero> Generos { get; set; }
        public DbSet<Pelicula> Peliculas { get; set; }
        public DbSet<Reserva> Reservas { get; set; }
        public DbSet<Sede> Sedes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TiposDocumento> TiposDocumentos { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<Versione> Versiones { get; set; }
    }
}
